export function load(){
    const logo = {url:"Logo.png", alt:"Leather in Style Logo"}
    const images = [
        {url:"1.jpg", alt:"image of a leather bag"},
        {url:"2.jpg", alt:"image of a leather bag"},
        {url:"3.jpg", alt:"image of a leather bag"},
        {url:"4.jpg", alt:"image of a leather bag"},
        {url:"5.jpg", alt:"image of a leather bag"},
        {url:"6.jpg", alt:"image of a leather bag"},
        {url:"7.jpg", alt:"image of a leather bag"},
        {url:"8.jpg", alt:"image of a leather bag"},
        {url:"9.jpg", alt:"image of a leather bag"},
        {url:"10.jpg", alt:"image of a leather bag"},        
        {url:"11.jpg", alt:"image of a leather bag"},
        {url:"12.jpg", alt:"image of a leather bag"},
        {url:"13.jpg", alt:"image of a leather bag"},
        {url:"14.jpg", alt:"image of a leather bag"},
        {url:"15.jpg", alt:"image of a leather bag"},
        {url:"16.jpg", alt:"image of a leather bag"},
        {url:"17.jpg", alt:"image of a leather bag"},
        {url:"18.jpg", alt:"image of a leather bag"},
        {url:"19.jpg", alt:"image of a leather bag"},
        {url:"20.jpg", alt:"image of a leather bag"},        
        {url:"21.jpg", alt:"image of a leather bag"},
        {url:"22.jpg", alt:"image of a leather bag"},
        {url:"23.jpg", alt:"image of a leather bag"},
        {url:"24.jpg", alt:"image of a leather bag"},
        {url:"25.jpg", alt:"image of a leather bag"},
        {url:"26.jpg", alt:"image of a leather bag"},
        {url:"27.jpg", alt:"image of a leather bag"},
        {url:"28.jpg", alt:"image of a leather bag"},
        {url:"29.jpg", alt:"image of a leather bag"},
        {url:"30.jpg", alt:"image of a leather bag"},        
        {url:"31.jpg", alt:"image of a leather bag"},
        {url:"32.jpg", alt:"image of a leather bag"},
        {url:"33.jpg", alt:"image of a leather bag"},
        {url:"34.jpg", alt:"image of a leather bag"},
        {url:"35.jpg", alt:"image of a leather bag"},
        {url:"36.jpg", alt:"image of a leather bag"},
        {url:"37.jpg", alt:"image of a leather bag"},
        {url:"38.jpg", alt:"image of a leather bag"},
        {url:"39.jpg", alt:"image of a leather bag"},
        {url:"40.jpg", alt:"image of a leather bag"},        
        {url:"41.jpg", alt:"image of a leather bag"},        
        {url:"42.jpg", alt:"image of a leather bag"},        
    ];

    return{
        images,
        baseURL: "https://ik.imagekit.io/YusufWebDev/Leather_in_Style/",
        logo
    }
}